In [1]:
import pandas as pd

ratings_df = pd.read_csv("../data/restaurant_data_reformatted/ratings.csv")
users_df = pd.read_csv("../data/restaurant_data_reformatted/users.csv")
restaurants_df = pd.read_csv("../data/restaurant_data_reformatted/restaurants.csv")

In [2]:
ratings_df

userID  placeID  rating  food_rating  service_rating
0     U1077   135085       2            2               2
1     U1077   135038       2            2               1
2     U1077   132825       2            2               2
3     U1077   135060       1            2               2
4     U1068   135104       1            1               2
...     ...      ...     ...          ...             ...
1156  U1043   132630       1            1               1
1157  U1011   132715       1            1               0
1158  U1068   132733       1            1               0
1159  U1068   132594       1            1               1
1160  U1068   132660       0            0               0

[1161 rows x 5 columns]

In [6]:
drop_cols = ['userID',
 'smoker',
 'drink_level',
 'dress_preference',
 'ambience',
 'transport',
 'marital_status',
 'hijos',
 'birth_year',
 'interest',
 'personality',
 'religion',
 'activity',
 'color',
 'weight',
 'budget',
 'height',
]

In [7]:
users_df.drop(drop_cols, axis=1)

Afghan  African  American  Armenian  Asian  Australian  Austrian  Bagels  \
0         0        0         1         0      0           0         0       0   
1         0        0         0         0      0           0         0       0   
2         0        0         0         0      0           0         0       0   
3         0        0         0         0      0           0         0       1   
4         0        0         1         0      0           0         0       0   
..      ...      ...       ...       ...    ...         ...       ...     ...   
133       0        0         0         0      0           0         0       0   
134       1        1         1         1      1           1         1       1   
135       0        0         0         0      0           0         0       0   
136       0        0         0         0      0           0         0       0   
137       0        0         0         0      0           0         0       0   

     Bakery  Bar  ...  Swiss  Tapas  Tea_House  Tex-Mex  Thai  Tibetan  \
0         0    0  ...      0      0          0        0     0        0   
1         0    0  ...      0      0          0        0     0        0   
2         0    0  ...      0      0          0        0     0        0   
3         1    0  ...      0      0          0        0     0        0   
4         0    0  ...      0      0          0        0     0        0   
..      ...  ...  ...    ...    ...        ...      ...   ...      ...   
133       0    0  ...      0      0          0        0     0        0   
134       1    1  ...      1      1          1        1     1        1   
135       0    0  ...      0      0          0        0     0        0   
136       0    0  ...      0      0          0        0     0        0   
137       0    0  ...      0      0          0        0     0        0   

     Tunisian  Turkish  Vegetarian  Vietnamese  
0           0        0           0           0  
1           0        0           0           0  
2           0        0           0           0  
3           0        0           0           0  
4           0        0           0           0  
..        ...      ...         ...         ...  
133         0        0           0           0  
134         1        1           1           1  
135         0        0           0           0  
136         0        0           0           0  
137         0        0           0           0  

[138 rows x 103 columns]

In [12]:
users_food_pref_df = users_df[restaurants_df.drop("placeID", axis=1).columns]

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

In [15]:
ans = cosine_similarity(users_food_pref_df, restaurants_df.drop("placeID", axis=1))

In [18]:
import numpy as np
np.sum(ans)

22418.728874880573

In [20]:
ans.shape

(138, 769)

In [21]:
ans

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
ans

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [32]:
tmp = ans[[0, 1]]
tmp

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [33]:
tmp[0][...][[0,1]]

array([0., 0.])

In [36]:
_m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
_m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
_us = _m[[0, 1]]
_us

array([[1, 2, 3],
       [4, 5, 6]])